### ISSUE TITLE
IOS build support

### ISSUE THREAD

**Issue by raindust** [elastos/Elastos.ELA.SPV.Cpp#132]

**Comment by ademcan** [comment]
I managed to create the Xcode project to build the wallet iOS library. Here are the different steps required:
$ git clone git@github.com:elastos/Elastos.ELA.SPV.Cpp.git
$ cd Elastos.ELA.SPV.Cpp
$ git submodule init
$ git submodule update
$ mkdir cmake-build-ios-release
$ cd cmake-build-ios-release
$ cmake -G Xcode ..

This will generate SPVSDK.xcodeproj under cmake-build-ios-release.
Open the Xcode project and start building the libraries.

However, I am having some issues while building the libraries, I will create new GitHub issues to list them.

**Comment by ademcan** [comment]
Sure, will do as soon as I have a working build for iOS, just so that it makes sense :)

**Comment by raindust** [comment]
That's great, @heropan and i will follow you, feel free to tell us if you have any questions :)

**Comment by raindust** [comment]
[Elastos.ORG.Wallet.Lib.C](https://github.com/elastos/Elastos.ORG.Wallet.Lib.C) is a subset of [Elastos.ELA.SPV.Cpp](https://github.com/elastos/Elastos.ELA.SPV.Cpp) for now which only have the basic functions for key and HD path deriving. This repo aims to provide a basic library for mobile DID capable apps to generate keys and IDs, and it is not a wallet library because it don't have storage module, merkle block definition and even the P2P communicating module. 
We are focus on android supporting recently, but you know there are so many IOS mobile devices we have no reason to abandon them (My mobile phone is IPhone too actually). So, what you are doing is very meaningful, hope this can help you and we can work together to make this repo better :)

**Comment by ademcan** [comment]
Ok I see. I will then prepare a PR with the modifications I made on the different files to be able to build for iOS. In the meantime, I explained here how to access the ELA wallet functionalities from React-Native using the C library. https://github.com/cyber-republic/elastos-ReactNative-framework/blob/master/doc/walletLibIos.md

**Comment by raindust** [comment]
Nice work👍

**Comment by raindust** [comment]
Hi @ademcan, thanks for your hard work. @heropan and i reviewed your PR together, we found some points should be improved within this PR, and also some points we can work together to improve later (listed in #607). Please check it :)

**Comment by ademcan** [comment]
Thanks. The recommendations are great, I will go through them in the coming days and update the PR accordingly.

**Comment by heropan** [comment]
Hi @ademcan, thank you very much for your PR(#606) and we appreciate your passion to contribute. We are deeply sorry that we can't wait for your PR because the community have strong needs for IOS version. According to your PR(#606), I created another PR(#617) to finish what you've started. 

 I didn't make it to support dynamic library for IOS too, we could consider it later.

Could you help to review my PR(#617) to check whether I missed anything?  Any suggestions are welcomed.

**Comment by ademcan** [comment]
Hi @heropan sorry for the long silence, I didn't have much time to come back to the work I did here although I wanted to finish it. 
I tried the PR(#617) from your fork and it works perfectly, I just had a simple quick comment. Thanks for your help👍

**Comment by ademcan** [comment]
Just copying my comment/question from the PR (https://github.com/elastos/Elastos.ELA.SPV.Cpp/pull/617):

@heropan I tried to build again and I still don't have a /lib folder inside cmake-build-ios/ that would contains the combined library. Am I missing something?

**Comment by heropan** [comment]
@ademcan Sorry for the delay.
I also noticed this issue and will follow up to find a solution.
Thanks for your info.

**Comment by heropan** [comment]
@ademcan I fixed the issue you mention before, please help to review the pr #627. thx
