### ISSUE TITLE
'system' is unavailable: not available on iOS

### ISSUE THREAD

**Issue by ademcan** [elastos/Elastos.ELA.SPV.Cpp#580]
After creating the Xcode project as explained here https://github.com/elastos/Elastos.ELA.SPV.Cpp/issues/132, I am having the following issue while building the libraries (ALL_BUILD) for iOS: 'system' is unavailable: not available on iOS. As a solution one can update the shell.c script as follow:

1. line 8771
replace 
rc = system(zCmd); 
by 
pid_t pid;
rc = posix_spawn(&pid, "", NULL, NULL, (char *const *) zCmd, NULL);

2. line 11689
replace 
if( system(zCmd) ){
by
pid_t pid;
if( posix_spawn(&pid, "", NULL, NULL, (char *const *) zCmd, NULL) ){

3. line 14723
replace 
x = system(zCmd);
by
pid_t pid;
x = posix_spawn(&pid, "", NULL, NULL, (char *const *) zCmd, NULL);

4. add at the beginning of the script:
#include <spawn.h>

Let me know if that seems correct to you.

**Comment by raindust** [comment]
Hi @ademcan. Thanks for the issue and details about improvement solution. 

I have tested on branch release_v0.3.0 (the latest release branch that will be merged to master soon), and found some build errors about the third party repo "fruit", this repo have not been used in the branch so i removed it temporarily.  After that i could successfully build on my side by [the commit of removing third party "fruit"](https://github.com/elastos/Elastos.ELA.SPV.Cpp/pull/584) (the sqlite3 repo can work on my PC).

Could you test again to let me know if this can work on your side.

**Comment by heropan** [comment]
@ademcan I think you can take a look at this repo [Apple-Boost-BuildScript](git@github.com:faithfracture/Apple-Boost-BuildScript.git). I don't suggest you to replace the Boost-for-Android, because it works fine for android platform. You can try to modify CMakeList.txt, ThirdParty/CMakeList.txt, ThirdParty/boost.cmake, etc. with repo Apple-Boost-BuildScript to support IOS.

**Comment by ademcan** [comment]
Perfect, that's exactly what I was doing (modifying the different CMakesLists.txt and *.cmake files accordingly). I will have a look at the repo and see how to integrate it for iOS support. Thanks.

**Comment by heropan** [comment]
Thank for your support, if you blocked by any problems, don't hesitate to let me know, I will try my best to help.
