### ISSUE TITLE
Building Failed. 

### ISSUE THREAD

**Issue by olivinesguerra** [elastos/Elastos.ELA.SPV.Cpp#633]
I'm using the Readme.md file on the Dev branch. 

I encounter this problem.

I followed this step.

$ cd /Users/xxx/dev/Elastos.ELA.SPV.Cpp
$ mkdir cmake-build-ios
$ cd cmake-build-ios
$ cmake -DSPV_PLATFORM=IOS ..
$ make -j 8

***************Logs Start ********************
-- Build spv for IOS
-- SPV build shared library -- OFF
-- Building with Xcode version: 10.1
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk for platform: OS
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using ar: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
-- Building for minimum iOS version: 10.0 (SDK version: 12.1)
-- Configuring iOS build for platform: OS, architecture(s): armv7;arm64
-- Building with Xcode version: 10.1
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using ar: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
-- Building for minimum iOS version: 10.0 (SDK version: 12.1)
-- Configuring iOS build for platform: OS, architecture(s): armv7;arm64
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
fatal: not a git repository (or any of the parent directories): .git
CMake Warning (dev) at CMakeLists.txt:13 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'SPV_BUILD_TEST_CASES'.
Call Stack (most recent call first):
  CMakeLists.txt:108 (option_with_default)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:13 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'SPV_BUILD_SAMPLE'.
Call Stack (most recent call first):
  CMakeLists.txt:109 (option_with_default)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:13 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'SPV_EXTRA_WARNINGS'.
Call Stack (most recent call first):
  CMakeLists.txt:112 (option_with_default)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at ThirdParty/fruit.cmake:8 (add_subdirectory):
  The source directory

    /Users/<User>/Desktop/Elastos.ELA.SPV.Cpp-dev/ThirdParty/fruit

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  ThirdParty/CMakeLists.txt:4 (include)

CMake Error at ThirdParty/fruit.cmake:9 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "fruit".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.
Call Stack (most recent call first):
  ThirdParty/CMakeLists.txt:4 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/<User>/Desktop/Elastos.ELA.SPV.Cpp-dev/cmake-build-ios/CMakeFiles/CMakeOutput.log".

***************Logs End ********************

Thanks.

**Comment by kpachhai** [comment]
I would recommend you not use that branch. Use this branch: https://github.com/elastos/Elastos.ELA.SPV.Cpp/tree/release_v0.3.0
THere's also a release for this if you look under "Releases"

**Comment by olivinesguerra** [comment]
thanks.
